# Nome do workflow que aparecerá no separador "Actions" do GitHub
name: CI - Testes e Qualidade do Código

# Define os gatilhos que acionam este workflow
on:
  # Aciona o workflow em pushes para qualquer ramo
  push:
    branches: ["**"]
  # Aciona também em pull requests para o ramo 'main'
  pull_request:
    branches: ["main"]

# Define os jobs que serão executados
jobs:
  # O nosso workflow tem apenas um job chamado 'test-and-lint'
  test-and-lint:
    # O tipo de máquina virtual onde o job será executado
    runs-on: ubuntu-latest

    # Os passos que compõem o job
    steps:
      # 1. Faz o checkout do código do seu repositório para a máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura o ambiente Python na versão especificada
      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Instala as dependências do projeto
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu

      # 4. Executa o linter (Flake8) para verificar a qualidade e estilo do código
      - name: Executar Linter com Flake8
        run: |
          # Procura por erros de sintaxe, imports não utilizados, etc.
          # O comando falhará se encontrar algum problema.
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # 5. Executa a suíte de testes com Pytest
      - name: Executar Testes com Pytest
        run: |
          pytest
